apiVersion: v1
kind: Service
metadata:
  name: product-producer
spec:
  selector:
    app: product-producer
  type: NodePort
  ports:
    - nodePort: 31235
      port: 8080
      protocol: TCP
      targetPort: 8080
