apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: search-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "https://demo-ff9654.es.europe-west3.gcp.cloud.es.io"
            - name: ELASTICSEARCH_USER
              value: elastic
            - name: ELASTICSEARCH_PASSWORD
              value: "2qZx5c67zQ1nDuyidJi87qHt"
          resources:
            limits:
              memory: 100Mi
              cpu: "1"
            requests:
              memory: 50Mi
              cpu: "0.2"
