apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: search-service
  type: NodePort
  ports:
    - nodePort: 31234
      port: 3000
      protocol: TCP
      targetPort: 3000
